const ELEMENT_DATA : LabdipChartVM[]=
[
  { 
    index:1,
    division :"PINK",
    season :"2022 Fall",
    category :"VSL LOUNGE",
    program :"",
    styleNoIndividual :"10226304",
    gMTDescription :"TIE ME UP ALLURE TANK",
    gMTColor :"140105OmbreLargeC0 05 5O10(10226304)",
    nRF :"5O10",
    colorCode :"",
    rMColor :"140105C005 5O10",
    packCombination :"",
    palcementName :"(INNER/OU TER) BODY, BODY LINING, STRAPPY DETAIL AT BACK",
    bOMSelection :"Fabric",
    itemName :"ZIPES44",
    supplierName :"HAYLEYS MGT KNITTING MILLS LTD",
    rMColorRef :"",
    garmentWay :"",
    fBNumber :"FB 6817",
    materialType :"Weft Interlock BRUSHED POSH POLY INTERLOC K FB 16021"
  },
  { 
    index:2,
    division :"PINK",
    season :"2022 Fall",
    category :"VSL LOUNGE",
    program :"",
    styleNoIndividual :"10226304",
    gMTDescription :"TIE ME UP ALLURE TANK",
    gMTColor :"140105OmbreLargeC0 05 5O10(10226304)",
    nRF :"5O40",
    colorCode :"",
    rMColor :"140105C005 5O10",
    packCombination :"",
    palcementName :"(INNER/OU TER) BODY, BODY LINING, STRAPPY DETAIL AT BACK",
    bOMSelection :"Fabric",
    itemName :"ZIPES44",
    supplierName :"HAYLEYS MGT KNITTING MILLS LTD",
    rMColorRef :"",
    garmentWay :"",
    fBNumber :"FB 6817",
    materialType :"Weft Interlock BRUSHED POSH POLY INTERLOC K FB 16021"
  },
  { 
    index:3,
    division :"PINK",
    season :"2022 Fall",
    category :"VSL LOUNGE",
    program :"",
    styleNoIndividual :"10226304",
    gMTDescription :"TIE ME UP ALLURE TANK",
    gMTColor :"140105OmbreLargeC0 05 5O10(10226304)",
    nRF :"5O19",
    colorCode :"",
    rMColor :"140105C005 5O10",
    packCombination :"",
    palcementName :"(INNER/OU TER) BODY, BODY LINING, STRAPPY DETAIL AT BACK",
    bOMSelection :"Fabric",
    itemName :"ZIPES44",
    supplierName :"HAYLEYS MGT KNITTING MILLS LTD",
    rMColorRef :"",
    garmentWay :"",
    fBNumber :"FB 6817",
    materialType :"Weft Interlock BRUSHED POSH POLY INTERLOC K FB 16021"
  },
  { 
    index:4,
    division :"PINK",
    season :"2022 Fall",
    category :"VSL LOUNGE",
    program :"",
    styleNoIndividual :"10226304",
    gMTDescription :"TIE ME UP ALLURE TANK",
    gMTColor :"140105OmbreLargeC0 05 5O10(10226304)",
    nRF :"5O1",
    colorCode :"",
    rMColor :"140105C005 5O10",
    packCombination :"",
    palcementName :"(INNER/OU TER) BODY, BODY LINING, STRAPPY DETAIL AT BACK",
    bOMSelection :"Fabric",
    itemName :"ZIPES44",
    supplierName :"HAYLEYS MGT KNITTING MILLS LTD",
    rMColorRef :"",
    garmentWay :"",
    fBNumber :"FB 6817",
    materialType :"Weft Interlock BRUSHED POSH POLY INTERLOC K FB 16021"
  },
  { 
    index:5,
    division :"PINK",
    season :"2022 Fall",
    category :"VSL LOUNGE",
    program :"",
    styleNoIndividual :"10226304",
    gMTDescription :"TIE ME UP ALLURE TANK",
    gMTColor :"140105OmbreLargeC0 05 5O10(10226304)",
    nRF :"5O1",
    colorCode :"",
    rMColor :"140105C005 5O10",
    packCombination :"",
    palcementName :"(INNER/OU TER) BODY, BODY LINING, STRAPPY DETAIL AT BACK",
    bOMSelection :"Fabric",
    itemName :"ZIPES44",
    supplierName :"HAYLEYS MGT KNITTING MILLS LTD",
    rMColorRef :"",
    garmentWay :"",
    fBNumber :"FB 6817",
    materialType :"Weft Interlock BRUSHED POSH POLY INTERLOC K FB 16021"
  },
  { 
    index:6,
    division :"PINK",
    season :"2022 Fall",
    category :"VSL LOUNGE",
    program :"",
    styleNoIndividual :"10226304",
    gMTDescription :"TIE ME UP ALLURE TANK",
    gMTColor :"140105OmbreLargeC0 05 5O10(10226304)",
    nRF :"5O1",
    colorCode :"",
    rMColor :"140105C005 5O10",
    packCombination :"",
    palcementName :"(INNER/OU TER) BODY, BODY LINING, STRAPPY DETAIL AT BACK",
    bOMSelection :"Fabric",
    itemName :"ZIPES44",
    supplierName :"HAYLEYS MGT KNITTING MILLS LTD",
    rMColorRef :"",
    garmentWay :"",
    fBNumber :"FB 6817",
    materialType :"Weft Interlock BRUSHED POSH POLY INTERLOC K FB 16021"
  },
];